"""sync all model fields

Revision ID: cac990cf23a4
Revises: 0004_profile_document_indexes
Create Date: 2026-04-22 07:02:49.455328
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cac990cf23a4'
down_revision: Union[str, None] = '0004_profile_document_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _has_column(table_name: str, column_name: str) -> bool:
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    return any(column.get("name") == column_name for column in inspector.get_columns(table_name))


def _add_column_if_missing(table_name: str, column: sa.Column) -> None:
    if not _has_column(table_name, column.name):
        op.add_column(table_name, column)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'is_verified',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_documents_extraction_status', table_name='documents', if_exists=True)
    op.drop_index('idx_documents_user_doc_type', table_name='documents', if_exists=True)
    op.drop_index('idx_documents_user_uploaded_at', table_name='documents', if_exists=True)
    op.create_index('idx_documents_user_type', 'documents', ['user_id', 'doc_type'], unique=False, if_not_exists=True)
    op.create_index('idx_eligibility_user_id', 'eligibility_results', ['user_id'], unique=False, if_not_exists=True)
    op.create_index('idx_eligibility_user_scheme', 'eligibility_results', ['user_id', 'scheme_id'], unique=True, if_not_exists=True)
    _add_column_if_missing('profiles', sa.Column('income_verified', sa.Integer(), nullable=True))
    _add_column_if_missing('profiles', sa.Column('income_source', sa.String(), nullable=True))
    op.alter_column('profiles', 'aadhaar_verified',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'bpl_status',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'is_household_head',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'has_bank_account',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'kcc_holder',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'crop_insurance',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'pm_kisan_registered',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'minority_status',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'is_woman_headed_household',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'onboarding_complete',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('profiles', 'onboarding_step',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.drop_index('idx_profiles_onboarding_step', table_name='profiles', if_exists=True)
    op.drop_index('idx_profiles_social_category', table_name='profiles', if_exists=True)
    op.drop_index('idx_profiles_state', table_name='profiles', if_exists=True)
    op.drop_index('idx_profiles_updated_at', table_name='profiles', if_exists=True)
    op.create_index('idx_profiles_user_id', 'profiles', ['user_id'], unique=True, if_not_exists=True)
    op.create_index('idx_applications_status', 'saved_applications', ['user_id', 'status'], unique=False, if_not_exists=True)
    op.create_index('idx_applications_user_id', 'saved_applications', ['user_id'], unique=False, if_not_exists=True)
    op.alter_column('schemes', 'myscheme_fallback',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('schemes', 'target_beneficiaries',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('schemes', 'csc_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('schemes', 'bank_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.alter_column('schemes', 'gram_panchayat_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_schemes_active_sector', 'schemes', ['is_active', 'sector'], unique=False, if_not_exists=True)
    op.create_index('idx_schemes_active_state', 'schemes', ['is_active', 'state'], unique=False, if_not_exists=True)
    _add_column_if_missing('users', sa.Column('name', sa.String(), nullable=True))
    _add_column_if_missing('users', sa.Column('is_admin', sa.Integer(), nullable=True))
    _add_column_if_missing('users', sa.Column('updated_at', sa.String(), nullable=True))
    op.alter_column('users', 'onboarding_incomplete',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    op.create_index('idx_users_email', 'users', ['email'], unique=True, if_not_exists=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_users_email', table_name='users')
    op.alter_column('users', 'onboarding_incomplete',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'name')
    op.drop_index('idx_schemes_active_state', table_name='schemes')
    op.drop_index('idx_schemes_active_sector', table_name='schemes')
    op.alter_column('schemes', 'gram_panchayat_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('schemes', 'bank_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.alter_column('schemes', 'csc_applicable',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=True)
    op.alter_column('schemes', 'target_beneficiaries',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('schemes', 'myscheme_fallback',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=True)
    op.drop_index('idx_applications_user_id', table_name='saved_applications')
    op.drop_index('idx_applications_status', table_name='saved_applications')
    op.drop_index('idx_profiles_user_id', table_name='profiles')
    op.create_index('idx_profiles_updated_at', 'profiles', ['updated_at'], unique=False)
    op.create_index('idx_profiles_state', 'profiles', ['state'], unique=False)
    op.create_index('idx_profiles_social_category', 'profiles', ['social_category'], unique=False)
    op.create_index('idx_profiles_onboarding_step', 'profiles', ['onboarding_step'], unique=False)
    op.alter_column('profiles', 'onboarding_step',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=True)
    op.alter_column('profiles', 'onboarding_complete',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'is_woman_headed_household',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'minority_status',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'pm_kisan_registered',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'crop_insurance',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'kcc_holder',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'has_bank_account',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'is_household_head',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'bpl_status',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.alter_column('profiles', 'aadhaar_verified',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    op.drop_column('profiles', 'income_source')
    op.drop_column('profiles', 'income_verified')
    op.drop_index('idx_eligibility_user_scheme', table_name='eligibility_results')
    op.drop_index('idx_eligibility_user_id', table_name='eligibility_results')
    op.drop_index('idx_documents_user_type', table_name='documents')
    op.create_index('idx_documents_user_uploaded_at', 'documents', ['user_id', 'uploaded_at'], unique=False)
    op.create_index('idx_documents_user_doc_type', 'documents', ['user_id', 'doc_type'], unique=False)
    op.create_index('idx_documents_extraction_status', 'documents', ['extraction_status'], unique=False)
    op.alter_column('documents', 'is_verified',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=True)
    # ### end Alembic commands ###
